version: '3'
services:
  app:
    container_name: app_messages
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9000:80
    volumes:
      - .:/var/www/html/app_messages
    environment:
      - UID=${UID}
      - GID=${GID}
    

