version: '3'
services:
  app:
    container_name: bookstore_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9000:80
    volumes:
      - .:/var/www/html/bookstore_api
    #network_mode: "host"
    environment:
      - UID=${UID}
      - GID=${GID}
    

